import React from 'react';
import {
  CreditCard,
  Car,
  FileText,
  Landmark,
  GraduationCap,
  UserCheck,
  Book,
  Shield,
  Lock,
  Wallet,
  Key,
  Fingerprint,
  Plane,
  Map,
  Briefcase,
  Heart,
  Home,
  Globe,
  PiggyBank,
  Receipt,
  Activity,
  Smartphone,
  Mail,
  Calendar,
  Zap,
  Wifi,
  Star,
  Gift,
  Archive,
  FolderOpen,
  Camera,
  Database,
  Cloud,
  Umbrella,
  Bell,
  Link,
  Paperclip,
  Folder,
  Tag,
  Smile,
  Award,
  Music,
  Video,
  Watch,
  Coffee,
  ShoppingBag,
  Truck,
  Cpu,
  HardDrive,
  ScanFace,
  ReceiptText,
} from 'lucide-react';

export const ICON_MAP: Record<string, React.ComponentType<{ className?: string }>> = {
  'file-text': FileText,
  'credit-card': CreditCard,
  'shield': Shield,
  'lock': Lock,
  'wallet': Wallet,
  'key': Key,
  'passport': Fingerprint,
  'fingerprint': Fingerprint,
  'scan-face': ScanFace,
  'landmark': Landmark,
  'graduation-cap': GraduationCap,
  'user-check': UserCheck,
  'car': Car,
  'plane': Plane,
  'map': Map,
  'briefcase': Briefcase,
  'heart': Heart,
  'home': Home,
  'globe': Globe,
  'piggy-bank': PiggyBank,
  'receipt': Receipt,
  'receipt-text': ReceiptText,
  'activity': Activity,
  'smartphone': Smartphone,
  'mail': Mail,
  'calendar': Calendar,
  'zap': Zap,
  'wifi': Wifi,
  'star': Star,
  'gift': Gift,
  'archive': Archive,
  'folder-open': FolderOpen,
  'folder': Folder,
  'camera': Camera,
  'database': Database,
  'cloud': Cloud,
  'umbrella': Umbrella,
  'bell': Bell,
  'link': Link,
  'paperclip': Paperclip,
  'book': Book,
  'tag': Tag,
  'smile': Smile,
  'award': Award,
  'music': Music,
  'video': Video,
  'watch': Watch,
  'coffee': Coffee,
  'shopping-bag': ShoppingBag,
  'truck': Truck,
  'cpu': Cpu,
  'hard-drive': HardDrive,
};

export function getCategoryIcon(iconName?: string, className: string = "w-5 h-5") {
  const IconComponent = (iconName && ICON_MAP[iconName.toLowerCase()]) || FileText;
  return <IconComponent className={className} />;
}
